/*
 * File: app/store/CompletedStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToDo.store.CompletedStore', {
    extend: 'Ext.data.Store',

    requires: [
        'ToDo.model.Task',
        'Ext.data.proxy.Sql',
        'Ext.util.Filter'
    ],

    config: {
        autoLoad: true,
        model: 'ToDo.model.Task',
        storeId: 'CompletedStore',
        proxy: {
            type: 'sql',
            database: 'ToDo',
            table: 'tasks'
        },
        filters: {
            filterFn: function(item) {
                return item.data.isCompleted;
            }
        }
    }
});