/*
 * File: app/view/DetailView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToDo.view.DetailView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.detailView',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.TextArea',
        'Ext.field.Hidden',
        'Ext.field.Select',
        'Ext.field.Toggle',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'fieldset',
                disabled: false,
                itemId: 'detailFieldSet',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'name',
                        label: 'Name',
                        name: 'name',
                        required: true
                    },
                    {
                        xtype: 'textareafield',
                        itemId: 'description',
                        label: 'Description',
                        name: 'description',
                        maxRows: 3
                    },
                    {
                        xtype: 'hiddenfield',
                        name: 'id'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'priority',
                        label: 'Priority',
                        name: 'priority',
                        options: [
                            {
                                text: 'High',
                                value: 1
                            },
                            {
                                text: 'Medium',
                                value: 2
                            },
                            {
                                text: 'Low',
                                value: 3
                            }
                        ]
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Done',
                        name: 'isCompleted'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'saveButton',
                margin: 10,
                ui: 'action-round',
                text: 'Save'
            },
            {
                xtype: 'button',
                itemId: 'deleteButton',
                margin: 10,
                ui: 'decline-round',
                text: 'Delete'
            }
        ]
    }

});