/*
 * File: app/controller/AddTask.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToDo.controller.AddTask', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            addTaskView: 'addTaskView',
            todoView: 'mainView #todoNavigationView'
        },

        control: {
            "addTaskView #saveButton": {
                tap: 'onSave'
            }
        }
    },

    onSave: function(button, e, eOpts) {
        console.log('Going to save new task');
        var todoView = this.getTodoView(),
            values = this.getAddTaskView().getValues(),
            store = Ext.getStore('TaskStore');

        values.isCompleted = false;
        store.add(values);
        // var record = Ext.create('ToDo.model.Task', values);
        // record.set('isCompleted', false);
        // store.add(record);
        store.sync();
        console.log('store.getCount():' + store.getCount());

        todoView.pop();
    }

});