/*
 * File: app/controller/Done.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToDo.controller.Done', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            doneView: 'mainView #doneNavigationView'
        },

        control: {
            "mainView #doneNavigationView #doneNavBar #clearAllButton": {
                tap: 'onClearAllButtonTap'
            },
            "mainView #doneNavigationView #doneList": {
                itemtap: 'onDoneListItemTap'
            }
        }
    },

    onClearAllButtonTap: function(button, e, eOpts) {
        var store = Ext.getStore('CompletedStore');
        store.removeAll();
        store.sync();
    },

    onDoneListItemTap: function(dataview, index, target, record, e, eOpts) {
        var doneView = this.getDoneView();

        var detailView = doneView.push({
            xtype: 'detailView',
            title: record.get('name'),
            record: record
        });

        detailView.down('#detailFieldSet').disable();
        detailView.down('#saveButton').hide();
    }

});