/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToDo.controller.Main', {
    extend: 'Ext.app.Controller',

    requires: [
        'ToDo.view.DetailView'
    ],

    config: {
        refs: {
            mainView: 'mainView',
            todoView: 'mainView #todoNavigationView'
        },

        control: {
            "mainView #todoNavigationView #todoList": {
                disclose: 'onListDisclose'
            }
        }
    },

    onListDisclose: function(list, record, target, index, e, eOpts) {
        var todoView = this.getTodoView();
            todoView.push({
                xtype: 'detailView',
                title: record.get('name'),
                record: record
            });
    }

});