/*
 * File: app/controller/ToDo.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToDo.controller.ToDo', {
    extend: 'Ext.app.Controller',

    requires: [
        'ToDo.view.DetailView',
        'ToDo.view.AddTaskView'
    ],

    config: {
        refs: {
            addTaskView: 'addTaskView',
            todoView: 'mainView #todoNavigationView'
        },

        control: {
            "mainView #todoNavigationView #todoList": {
                itemtap: 'onListItemTap',
                show: 'onListShow',
                itemswipe: 'onListItemSwipe'
            },
            "mainView #todoNavigationView #todoNavBar #addButton": {
                tap: 'onAddButtonTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        var todoView = this.getTodoView();
        this.getTodoView().down('#todoNavBar #addButton').hide();
        console.log('going to push the record');

        todoView.push({
            xtype: 'detailView',
            title: record.get('name'),
            record: record
        });
    },

    onAddButtonTap: function(button, e, eOpts) {
        console.log('onAddButtonTap');
        var todoView = this.getTodoView();
        this.getTodoView().down('#todoNavBar #addButton').hide();
        todoView.push({
                    xtype: 'addTaskView',
                    title: 'Add a new task',
                });
    },

    onListShow: function(component, eOpts) {
        this.getTodoView().down('#todoNavBar #addButton').show();
    },

    onListItemSwipe: function(dataview, index, target, record, e, eOpts) {
        console.log('list item swipe');
        var actionSheet = Ext.create('Ext.ActionSheet', {
            items: [
                {
                    text: 'Done',
                    ui  : 'confirm',
                    handler: function(button, e, eOpts) {
                        var record = actionSheet.getRecord(),
                        store = Ext.getStore('TaskStore');
                        store.remove(record);
                        store.sync();

                        actionSheet.hide();
                        console.log('task deleted');
                    }
                },
                {
                    text: 'Cancel',
                    ui  : 'decline',
                    handler: function() {actionSheet.hide();}
                }
            ]
        });

        actionSheet.setRecord(record);
        Ext.Viewport.add(actionSheet);
        actionSheet.show();
    }

});